# Generated by Django 4.0.4 on 2022-06-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('date_joined', models.DateField()),
                ('next_of_kin', models.CharField(max_length=200, null=True)),
                ('next_of_kin_Phone', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
