# Generated by Django 4.0.4 on 2022-06-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Pending', 'Pending')], max_length=300)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
        ),
    ]
